# Generated by cpp11: do not edit by hand

get_diff_rows_int <- function(vec_a, vec_b, idx_a, idx_b) {
  .Call(`_versus_get_diff_rows_int`, vec_a, vec_b, idx_a, idx_b)
}

get_diff_rows_dbl <- function(vec_a, vec_b, idx_a, idx_b) {
  .Call(`_versus_get_diff_rows_dbl`, vec_a, vec_b, idx_a, idx_b)
}
